version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: todo_app
      MYSQL_PASSWORD: root123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  backend:
    build:
      context: ./backend
    container_name: todo-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: todo-mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: todo_app
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: "http://localhost:5000/api"
    container_name: todo-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mysql_data:

networks:
  todo-network:
    driver: bridge
